### PR TITLE
Config rewrite

### PR DESCRIPTION
**Pull request by xcb-xwii**
see #61
see https://github.com/Evergreen-lxl/evergreen-languages
maybe can be used as basis to implement features from #54

### CODE REVIEW

**Comment by TorchedSammy** [comment]
some queries will have predicates that currently arent supported, which means the c and cpp languages would not work.

**Comment by xcb-xwii** [comment]
> some queries that are pulled from nvim-treesitter will have predicates that currently arent supported, which means languages like c and cpp would not work.

#66

**Comment by xcb-xwii** [comment]
There's also some new highlight groups that need to be supported.

Will probably combine this with a fix for #65. Really need a more robust colour system.

**Comment by xcb-xwii** [comment]
fixes #65

**Comment by xcb-xwii** [comment]
This should be ready.

Unless we want to add back an installer? But I think that should be its own PR.

**Pull request merged**
